Repository Dashlane/dashlane-cli, pull requests merged in 2023-03, with the labels that each got.

#62 Adding more issue cases to documentation
  README.md
Labels: documentation

#63 Use stderr for interactive prompts
  src/index.ts
  src/middleware/getPasswords.ts
  src/middleware/getSecureNotes.ts
  src/middleware/registerDevice.ts
  src/utils/dialogs.ts
  src/utils/index.ts
  src/utils/strings.ts
Labels: enhancement

#70 Add safe guards for inputs
  src/middleware/registerDevice.ts
  src/utils/dialogs.ts
Labels: bug

#73 Migration to Rust deps and Yarn
  .github/workflows/manual-test-release.yml
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .gitignore
  .husky/pre-commit
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  README.md
  package-lock.json
  package.json
  prepare-pkg.sh
  src/crypto/decrypt.ts
  src/crypto/keychainManager.ts
  src/database/connectAndPrepare.ts
  src/index.ts
  src/middleware/configure.ts
  src/middleware/reset.ts
  yarn.lock
Labels: enhancement

#74 Migrate clipboard to rust
  README.md
  package.json
  src/middleware/getPasswords.ts
  yarn.lock
Labels: enhancement

#76 Optimize package builds
  .github/workflows/manual-test-release.yml
  .github/workflows/release.yml
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarnrc.yml
Labels: enhancement

#77 Update clipboard for WSL support
  package.json
  yarn.lock
Labels: enhancement

#84 Correctly handle password retrieval when no filters are provided
  src/middleware/getPasswords.ts
Labels: bug

#85 Correct the message when retrieving credentials without specifying filters
  src/middleware/getPasswords.ts
Labels: invalid

#95 Stop using GetAuditLogs endpoint.
  src/endpoints/getAuditLogs.ts
  src/index.ts
  src/middleware/getAuditLogs.ts
Labels: enhancement

#96 feat(devices): add list and remove devices commands
  package.json
  src/command-handlers/devices.ts
  src/command-handlers/index.ts
  src/endpoints/deactivateDevices.ts
  src/endpoints/index.ts
  src/endpoints/listDevices.ts
  src/index.ts
Labels: enhancement
