Repository Dashlane/dashlane-cli, pull requests merged in 2024-06, with the labels that each got.

#252 Make a tsc plugin for esbuild
  .github/workflows/manual-test-release.yml
  .github/workflows/release.yml
  package.json
  scripts/build.js
  tsconfig.build.json
  yarn.lock
Labels: platform

#255 Platform/update depdencies jun 2024
  .eslintrc.json
  .github/workflows/manual-test-release.yml
  .github/workflows/release.yml
  README.md
  eslint.config.mjs
  package.json
  src/command-handlers/configure.ts
  src/modules/auth/userPresenceVerification.ts
  yarn.lock
Labels: platform

#256 Add integrations documentation
  documentation/package.json
  documentation/pages/_meta.json
  documentation/pages/index.mdx
  documentation/pages/integrations.mdx
  documentation/pages/integrations/_meta.json
  documentation/pages/integrations/github-action.mdx
  documentation/pages/integrations/siem.mdx
  documentation/pages/integrations/vscode.mdx
  documentation/pages/personal.mdx
  documentation/pages/personal/_meta.json
  documentation/pages/personal/authentication.mdx
  documentation/pages/personal/logout.mdx
  documentation/yarn.lock
Labels: documentation

#261 Fix lint CI trigger
  .github/workflows/tests.yml
  src/modules/database/vaultContent.ts
Labels: bug

#264 Prevent spawn child to be terminated by parent
  src/command-handlers/exec.ts
Labels: bug

#265 Use new domain cli.dashlane.com
  README.md
  documentation/next.config.js
  documentation/pages/integrations/github-action.mdx
  documentation/pages/integrations/siem.mdx
  documentation/theme.config.jsx
Labels: documentation

#268 (Feature) Allow user-device and team-device auth for calls through secure tunnel
  src/modules/auth/confidential-sso/index.ts
  src/modules/tunnel-api-connect/steps/sendSecureContent.ts
  src/modules/tunnel-api-connect/steps/types.ts
  src/modules/tunnel-api-connect/types.ts
  src/requestApi.ts
Labels: features
