Repository Dashlane/dashlane-cli, pull requests merged in 2024-08, with the labels that each got.

#274 (Feature) Get team audit logs through secure tunnel
  documentation/pages/business/audit-logs.mdx
  src/command-handlers/teamLogs.ts
  src/commands/team/index.ts
  src/endpoints/getAuditLogs.ts
  src/modules/auth/confidential-sso/index.ts
  src/modules/tunnel-api-connect/apiconnect.ts
  src/modules/tunnel-api-connect/steps/terminateHello.ts
  src/modules/tunnel-api-connect/steps/types.ts
  src/modules/tunnel-api-connect/types.ts
Labels: features

#276 Add audit logs for item usage events to audit-logs.mdx
  documentation/pages/business/audit-logs.mdx
Labels: documentation

#279 Remove dashlane_authenticator 2FA path
  src/endpoints/index.ts
  src/endpoints/performDashlaneAuthenticatorVerification.ts
  src/modules/auth/registerDevice.ts
Labels: bug
