Repository Dashlane/dashlane-cli, pull requests merged in 2024-03, with the labels that each got.

#216 Add option to fetch login or email
  README.md
  documentation/pages/personal/vault.mdx
  src/command-handlers/passwords.ts
  src/commands/index.ts
Labels: features

#217 Merge `otp` command with `password`
  src/command-handlers/passwords.ts
  src/commands/index.ts
Labels: features

#218 Migrate to new team device keys format
  documentation/pages/business/index.mdx
  src/command-handlers/passwords.ts
  src/command-handlers/teamDevices.ts
  src/commands/team/credentials.ts
  src/errors.ts
  src/utils/teamDeviceCredentials.ts
Labels: features

#219 Fix: url encode login at device registration
  src/modules/auth/registerDevice.ts
Labels: bug

#220 Migrate to service device keys format
  documentation/pages/personal/devices.mdx
  src/command-handlers/devices.ts
  src/errors.ts
  src/utils/deviceCredentials.ts
Labels: features

#222 Fix non-interactive devices first login
  src/modules/database/connectAndPrepare.ts
Labels: bug

#223 Support Master Password authentication via env variable
  src/modules/crypto/keychainManager.ts
Labels: features

#224 Dependencies upgrade march 24
  .husky/pre-commit
  package.json
  src/modules/crypto/keychainManager.ts
  yarn.lock
Labels: platform

#225 Prevent API call non-interactive device login
  src/modules/crypto/keychainManager.ts
Labels: bug

#226 Update documentation dependencies
  documentation/package.json
  documentation/yarn.lock
Labels: platform

#227 Update documentation once released
  .github/workflows/documentation-deploy.yml
Labels: platform

#228 Cleanup documentation with latest changes
  documentation/pages/business/index.mdx
  documentation/pages/business/members.mdx
  documentation/pages/install.mdx
  documentation/pages/logout.mdx
  documentation/pages/personal/authentication.mdx
  documentation/pages/personal/backup.mdx
  documentation/pages/personal/devices.mdx
  documentation/pages/personal/secrets/inject.mdx
  documentation/pages/personal/secrets/read.mdx
  documentation/pages/personal/vault.mdx
Labels: documentation

#229 fix: Support Master Password authentication via env variable
  src/modules/crypto/keychainManager.ts
Labels: bug

#231 Implement user presence verification with biometrics
  package.json
  src/command-handlers/configure.ts
  src/commands/configure.ts
  src/index.ts
  src/modules/auth/index.ts
  src/modules/auth/userPresenceVerification.ts
  src/modules/crypto/keychainManager.ts
  src/modules/database/connectAndPrepare.ts
  src/modules/database/prepare.ts
  src/types.ts
  src/types/node-mac-auth.d.ts
  yarn.lock
Labels: features
